// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xkqzwdubkxutogqcnapm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhrcXp3ZHVia3h1dG9ncWNuYXBtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzODg5MjgsImV4cCI6MjA2MDk2NDkyOH0.iSmeuNatP0gYIWNk_fYTX6HxzHgCo-8zj5HJW3WHgN0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);